services:
  backend:
    image: ghcr.io/xwillq/dev-environment/php/8.1-fpm:latest
    container_name: ${APP_NAME}
    restart: on-failure
    environment:
      PHP_IDE_CONFIG: serverName=${APP_NAME}
      PHP_MEMORY_LIMIT: 128M

      # Фикс ссылок на редактирование файлов на странице ошибки
      IGNITION_REMOTE_SITES_PATH: /app
      IGNITION_LOCAL_SITES_PATH: ${PWD}
    volumes:
      - code:/app
    networks:
      - main

  server:
    image: ghcr.io/xwillq/dev-environment/nginx:latest
    restart: on-failure
    environment:
      NGINX_PORT: 8080
      PHP_HOST: ${APP_NAME}
      PUBLIC_DIR: /app/public
    volumes:
      - ./:/app
    networks:
      - main
    labels:
      - traefik.enable=true

      - traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${APP_NAME}.entrypoints=websecure
      - traefik.http.services.${APP_NAME}.loadbalancer.server.port=8080

  default-queue:
    image: ghcr.io/xwillq/dev-environment/php/8.1-fpm:latest
    restart: on-failure
    user: www-data
    environment:
      PHP_IDE_CONFIG: serverName=${APP_NAME}
      PHP_MEMORY_LIMIT: 128M
    volumes:
      - ./:/app
    networks:
      - main
    command: php artisan queue:listen --timeout 3600 --memory 128 --queue default


networks:
  main:
    external: true
    name: main

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      scanMode: full
      ignore:
        paths:
          - "*.sql"
      mode: two-way-resolved

    code:
      alpha: .
      configurationAlpha:
        permissions:
          defaultFileMode: 0o644
          defaultDirectoryMode: 0o755
      beta: volume://code
      configurationBeta:
        permissions:
          defaultOwner: id:82
          defaultGroup: id:82
          defaultFileMode: 0o644
          defaultDirectoryMode: 0o755

  sidecar:
    restart: on-failure
