services:
  traefik:
    image: traefik:v2.7
    container_name: traefik
    restart: always
    logging:
      driver: local
    environment:
      LEGO_CA_CERTIFICATES: /certs/root_ca.crt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik
      - traefik-acme:/var/acme
      - certificates:/certs
    networks:
      main:
        ipv4_address: 172.19.128.1
    ports:
      - 80:80
      - 443:443


networks:
  main:
    external: true
    name: main

volumes:
  traefik-acme:
  certificates:
    external: true
    name: certificates

