services:
  backend:
    image: ghcr.io/xwillq/dev-environment/php/7.4-nginx:latest
    container_name: ${APP_NAME}
    restart: on-failure
    logging:
      driver: local
    environment:
      PHP_IDE_CONFIG: serverName=${APP_NAME}
      PHP_MEMORY_LIMIT: 128M

      # Фикс ссылок на редактирование файлов на странице ошибки
      IGNITION_REMOTE_SITES_PATH: /app
      IGNITION_LOCAL_SITES_PATH: ${PWD}
    volumes:
      - ./:/app
    networks:
      - main
    labels:
      - traefik.enable=true

      - traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${APP_NAME}.entrypoints=websecure
      - traefik.http.services.${APP_NAME}.loadbalancer.server.port=80

  default-queue:
    image: ghcr.io/xwillq/dev-environment/php/7.4-nginx:latest
    restart: on-failure
    user: www-data
    logging:
      driver: local
    environment:
      PHP_IDE_CONFIG: serverName=${APP_NAME}
      PHP_MEMORY_LIMIT: 128M
    volumes:
      - ./:/app
    networks:
      - main
    command: php artisan queue:listen --timeout 3600 --memory 128 --queue default

  echo-server:
    image: oanhnn/laravel-echo-server
    restart: on-failure
    logging:
      driver: local
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: http://${APP_NAME}
      LARAVEL_ECHO_SERVER_REDIS_HOST: redis
      LARAVEL_ECHO_SERVER_REDIS_PORT: 6379
    volumes:
      - echo-server:/app
      - ./echo-server.json:/app/laravel-echo-server.json
    networks:
      - main
    labels:
      - traefik.enable=true

      - traefik.http.routers.${APP_NAME}-echo-server.rule=Host(`${DOMAIN}`) && PathPrefix(`/socket.io`)
      - traefik.http.routers.${APP_NAME}-echo-server.entrypoints=websecure
      - traefik.http.services.${APP_NAME}-echo-server.loadbalancer.server.port=6001


networks:
  main:
    external: true
    name: main

volumes:
  echo-server:
