services:
  backend:
    image: ghcr.io/xwillq/dev-environment/php/8.1-rr:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: on-failure
    environment:
      PHP_IDE_CONFIG: serverName=${APP_NAME}
      PHP_MEMORY_LIMIT: 128M

      # Переменные из Octane
      APP_BASE_PATH: /app
      APP_ENV: ${APP_ENV}
      LARAVEL_OCTANE: 1

      # Фикс ссылок на редактирование файлов на странице ошибки
      IGNITION_REMOTE_SITES_PATH: /app
      IGNITION_LOCAL_SITES_PATH: ${PWD}
    volumes:
      - ./:/app
    networks:
      - main
    command: rr serve -o http.pool.supervisor.max_worker_memory=128
    labels:
      - traefik.enable=true

      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8000

  default-queue:
    image: ghcr.io/xwillq/dev-environment/php/8.1-rr:latest
    restart: on-failure
    environment:
      PHP_IDE_CONFIG: serverName=${APP_NAME}
      PHP_MEMORY_LIMIT: 128M
    volumes:
      - ./:/app
    networks:
      - main
    command: php artisan queue:listen --timeout 3600 --memory 128 --queue default


networks:
  main:
    external: true
    name: main
