services:
  backend:
    image: ghcr.io/xwillq/dev-environment/php/8.1-rr:latest
    container_name: ${APP_NAME}
    restart: on-failure
    logging:
      driver: local
    environment:
      PHP_IDE_CONFIG: serverName=${DOMAIN}
      PHP_MEMORY_LIMIT: 128M

      # Переменные из Octane
      APP_BASE_PATH: /app
      APP_ENV: ${APP_ENV}
      LARAVEL_OCTANE: 1
    volumes:
      - code:/app
    networks:
      - main
    command: rr serve -o http.pool.supervisor.max_worker_memory=128
    labels:
      - traefik.enable=true

      - traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${APP_NAME}.entrypoints=websecure
      - traefik.http.services.${APP_NAME}.loadbalancer.server.port=8000

  default-queue:
    image: ghcr.io/xwillq/dev-environment/php/8.1-rr:latest
    restart: on-failure
    user: www-data
    logging:
      driver: local
    environment:
      PHP_IDE_CONFIG: serverName=${DOMAIN}
      PHP_MEMORY_LIMIT: 128M
    volumes:
      - code:/app
    networks:
      - main
    command: php artisan queue:listen --timeout 3600 --memory 128 --queue default

  echo-server:
    image: oanhnn/laravel-echo-server
    restart: on-failure
    logging:
      driver: local
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: http://${APP_NAME}
      LARAVEL_ECHO_SERVER_REDIS_HOST: redis
      LARAVEL_ECHO_SERVER_REDIS_PORT: 6379
    volumes:
      - echo-server:/app
      - ./echo-server.json:/app/laravel-echo-server.json
    networks:
      - main
    labels:
      - traefik.enable=true

      - traefik.http.routers.${APP_NAME}-echo-server.rule=Host(`${DOMAIN}`) && PathPrefix(`/socket.io`)
      - traefik.http.routers.${APP_NAME}-echo-server.entrypoints=websecure
      - traefik.http.services.${APP_NAME}-echo-server.loadbalancer.server.port=6001


networks:
  main:
    external: true
    name: main

volumes:
  code:
  echo-server:

x-mutagen:
  sync:
    defaults:
      scanMode: full
      ignore:
        vcs: true
        paths:
          - "*.sql"
      mode: two-way-resolved

    code:
      alpha: .
      configurationAlpha:
        permissions:
          defaultFileMode: 0o644
          defaultDirectoryMode: 0o755
      beta: volume://code
      configurationBeta:
        permissions:
          defaultOwner: id:82
          defaultGroup: id:82
          defaultFileMode: 0o644
          defaultDirectoryMode: 0o755

  sidecar:
    restart: on-failure
