services:
  frontend:
    image: nginx:1.20-alpine
    container_name: ${APP_NAME}
    restart: unless-stopped
    logging:
      driver: local
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/app
    networks:
      - main
    labels:
      - traefik.enable=true

      - traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${APP_NAME}.entrypoints=websecure
      - traefik.http.services.${APP_NAME}.loadbalancer.server.port=80


networks:
  main:
    external: true
    name: main
