services:
  node:
    image: ghcr.io/xwillq/dev-environment/node:latest
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - main


networks:
  main:
    external: true
    name: main
