services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    logging:
      driver: local
    environment:
      LEGO_CA_CERTIFICATES: /certs/root_ca.crt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik
      - traefik-acme:/var/acme
      - ./ca/certs:/certs
    networks:
      main:
        ipv4_address: 172.92.128.1
    ports:
      - 80:80
      - 443:443

  step-ca:
    image: step-ca
    container_name: step-ca
    build: ./images/step-ca
    restart: always
    logging:
      driver: local
    environment:
      DOCKER_STEPCA_INIT_NAME: Localhost
      DOCKER_STEPCA_INIT_ADDRESS: ":9000"
      DOCKER_STEPCA_INIT_DNS_NAMES: step-ca
      DOCKER_STEPCA_INIT_PASSWORD: ${DOCKER_STEPCA_INIT_PASSWORD}
      DOCKER_STEPCA_INIT_ACME: true
    volumes:
      - ./ca:/home/step
    networks:
      - main
    dns: 127.0.0.1


networks:
  main:
    external: true
    name: main

volumes:
  traefik-acme:
