services:
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
    networks:
      - main
    command: server /data --console-address ":9001"
    labels:
      - traefik.enable=true

      - traefik.http.routers.minio.rule=Host(`minio.test`)
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.services.minio.loadbalancer.server.port=9001


networks:
  main:
    external: true
    name: main

